name       : haskell-blaze-html
version    : 0.9.0.1
release    : 2
source     :
    - http://hackage.haskell.org/package/blaze-html-0.9.0.1/blaze-html-0.9.0.1.tar.gz : aeceaab3fbccbf7f01a241819e6c16c0a1cf19dccecb795c5de5407bc8660a64
license    : BSD-3-Clause
component  : programming.haskell
summary    : A blazingly fast HTML combinator library for the Haskell programming
    language.
description: |
    A blazingly fast HTML combinator library for the Haskell programming language.
builddeps  :
    - haskell-blaze-markup
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
