name       : haskell-blaze-html
version    : 0.9.1.2
release    : 3
source     :
    - https://hackage.haskell.org/package/blaze-html-0.9.1.2/blaze-html-0.9.1.2.tar.gz : 60503f42546c6c1b954014d188ea137e43d74dcffd2bf6157c113fd91a0c394c
license    : BSD-3-Clause
component  : programming.haskell
summary    : A blazingly fast HTML combinator library for the Haskell programming language.
description: |
    A blazingly fast HTML combinator library for the Haskell programming language.
builddeps  :
    - haskell-blaze-markup-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - haskell-blaze-markup-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
